/**
 * OpenClaw local readiness route.
 *
 * Serves the latest local smoke readiness snapshot for Mission Control.
 * Source artifacts are generated by scripts/openclaw-local-smoke.sh.
 */

import fs from 'node:fs';
import path from 'node:path';

import type { IncomingMessage, ServerResponse } from 'node:http';

export interface OpenclawLocalReadinessDeps {
  reportDir: string;
  sendJson: (res: ServerResponse, data: unknown, status?: number) => void;
}

type CheckStatus = 'pass' | 'fail' | 'skipped';
type CheckSeverity = 'critical' | 'critical-optional' | 'warn' | 'info';
type Verdict = 'go' | 'hold' | 'blocked';
type Confidence = 'high' | 'medium' | 'low';

interface ReadinessCheck {
  id: string;
  required: boolean;
  status: CheckStatus;
  durationMs: number;
  description: string;
  detail: string;
  group: string;
  severity: CheckSeverity;
  likelyCause: string;
  nextCommand: string;
  owner: string;
}

interface GroupSummary {
  id: string;
  total: number;
  pass: number;
  fail: number;
  skipped: number;
}

const REPORT_PATTERN = /^openclaw-local-smoke-(\d{8}T\d{6}Z)\.json$/;
const SEVERITY_RANK: Record<CheckSeverity, number> = {
  critical: 4,
  'critical-optional': 3,
  warn: 2,
  info: 1,
};

export function resolveOpenclawLocalReadinessReportDir(
  ventureosRoot: string,
  env: NodeJS.ProcessEnv = process.env,
): string {
  const explicit = (env.OPENCLAW_LOCAL_READINESS_REPORT_DIR ?? '').trim();
  if (explicit) return explicit;
  return path.join(ventureosRoot, 'runtime', 'reports', 'openclaw-local-smoke');
}

function toRecord(value: unknown): Record<string, unknown> | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  return value as Record<string, unknown>;
}

function toStringValue(value: unknown, fallback: string): string {
  if (typeof value === 'string') {
    const trimmed = value.trim();
    return trimmed || fallback;
  }
  if (typeof value === 'number' && Number.isFinite(value)) return String(value);
  return fallback;
}

function toNonNegativeInt(value: unknown, fallback: number): number {
  if (typeof value === 'number' && Number.isFinite(value)) {
    return Math.max(0, Math.round(value));
  }
  const parsed = Number.parseInt(String(value ?? ''), 10);
  if (Number.isFinite(parsed)) return Math.max(0, parsed);
  return fallback;
}

function normalizeStatus(value: unknown): CheckStatus {
  const raw = toStringValue(value, 'skipped').toLowerCase();
  if (raw === 'pass' || raw === 'fail' || raw === 'skipped') return raw;
  return 'skipped';
}

function normalizeSeverity(value: unknown): CheckSeverity {
  const raw = toStringValue(value, 'info').toLowerCase();
  if (raw === 'critical' || raw === 'critical-optional' || raw === 'warn' || raw === 'info') return raw;
  return 'info';
}

function normalizeVerdict(value: unknown): Verdict {
  const raw = toStringValue(value, 'blocked').toLowerCase();
  if (raw === 'go' || raw === 'hold' || raw === 'blocked') return raw;
  return 'blocked';
}

function normalizeConfidence(value: unknown): Confidence {
  const raw = toStringValue(value, 'low').toLowerCase();
  if (raw === 'high' || raw === 'medium' || raw === 'low') return raw;
  return 'low';
}

function listTimestamps(reportDir: string): string[] {
  if (!fs.existsSync(reportDir)) return [];
  const entries = fs.readdirSync(reportDir);
  const out: string[] = [];
  for (const entry of entries) {
    const match = entry.match(REPORT_PATTERN);
    if (match) out.push(match[1]);
  }
  return out.sort((a, b) => b.localeCompare(a));
}

function loadLatestReport(reportDir: string): { timestamp: string; fileName: string; payload: Record<string, unknown> } | null {
  const timestamps = listTimestamps(reportDir);
  if (timestamps.length === 0) return null;
  const timestamp = timestamps[0];
  const fileName = `openclaw-local-smoke-${timestamp}.json`;
  const filePath = path.join(reportDir, fileName);
  const text = fs.readFileSync(filePath, 'utf8');
  const parsed = JSON.parse(text) as unknown;
  const payload = toRecord(parsed);
  if (!payload) throw new Error('Latest smoke report is not a JSON object');
  return { timestamp, fileName, payload };
}

function normalizeChecks(rawChecks: unknown): ReadinessCheck[] {
  if (!Array.isArray(rawChecks)) return [];
  return rawChecks.map((raw, index) => {
    const row = toRecord(raw) ?? {};
    return {
      id: toStringValue(row.id, `check-${index + 1}`),
      required: Boolean(row.required),
      status: normalizeStatus(row.status),
      durationMs: toNonNegativeInt(row.durationMs, 0),
      description: toStringValue(row.description, 'Unnamed check'),
      detail: toStringValue(row.detail, ''),
      group: toStringValue(row.group, 'core'),
      severity: normalizeSeverity(row.severity),
      likelyCause: toStringValue(row.likelyCause, 'Unknown failure cause.'),
      nextCommand: toStringValue(row.nextCommand, 'Inspect logs and rerun readiness smoke.'),
      owner: toStringValue(row.owner, 'Unassigned'),
    };
  });
}

function summarizeGroups(checks: ReadinessCheck[]): GroupSummary[] {
  const map = new Map<string, GroupSummary>();
  for (const check of checks) {
    const group = check.group || 'core';
    if (!map.has(group)) {
      map.set(group, {
        id: group,
        total: 0,
        pass: 0,
        fail: 0,
        skipped: 0,
      });
    }
    const current = map.get(group)!;
    current.total += 1;
    if (check.status === 'pass') current.pass += 1;
    if (check.status === 'fail') current.fail += 1;
    if (check.status === 'skipped') current.skipped += 1;
  }
  return Array.from(map.values()).sort((a, b) => a.id.localeCompare(b.id));
}

function selectTopBlockers(checks: ReadinessCheck[]): Array<Record<string, unknown>> {
  const failed = checks.filter((check) => check.status === 'fail');
  failed.sort((a, b) => {
    if (a.required !== b.required) return a.required ? -1 : 1;
    const sev = (SEVERITY_RANK[b.severity] ?? 0) - (SEVERITY_RANK[a.severity] ?? 0);
    if (sev !== 0) return sev;
    return b.durationMs - a.durationMs;
  });
  return failed.slice(0, 3).map((check) => ({
    id: check.id,
    required: check.required,
    severity: check.severity,
    owner: check.owner,
    description: check.description,
    detail: check.detail,
    likelyCause: check.likelyCause,
    nextCommand: check.nextCommand,
  }));
}

export function handleOpenclawLocalReadiness(
  req: IncomingMessage,
  res: ServerResponse,
  deps: OpenclawLocalReadinessDeps,
): boolean {
  if (!req.url || req.method !== 'GET') return false;
  if (!req.url.startsWith('/api/openclaw-local-readiness')) return false;

  try {
    const routeUrl = new URL(req.url, 'http://localhost');
    if (routeUrl.pathname !== '/api/openclaw-local-readiness') return false;
  } catch {
    deps.sendJson(res, { ok: false, error: 'Bad request' }, 400);
    return true;
  }

  try {
    const latest = loadLatestReport(deps.reportDir);
    if (!latest) {
      deps.sendJson(res, {
        ok: true,
        available: false,
        reason: 'no-artifacts',
      });
      return true;
    }

    const summary = toRecord(latest.payload.summary) ?? {};
    const checks = normalizeChecks(latest.payload.checks);
    const summaryPayload = {
      profile: toStringValue(summary.profile, 'full'),
      requiredFailures: toNonNegativeInt(summary.requiredFailures, 0),
      requiredSkipped: toNonNegativeInt(summary.requiredSkipped, 0),
      warnings: toNonNegativeInt(summary.warnings, 0),
      totalChecks: toNonNegativeInt(summary.totalChecks, checks.length),
      passCount: toNonNegativeInt(summary.passCount, checks.filter((c) => c.status === 'pass').length),
      failCount: toNonNegativeInt(summary.failCount, checks.filter((c) => c.status === 'fail').length),
      skippedCount: toNonNegativeInt(summary.skippedCount, checks.filter((c) => c.status === 'skipped').length),
      verdict: normalizeVerdict(summary.verdict),
      readinessScore: Math.max(0, Math.min(100, toNonNegativeInt(summary.readinessScore, 0))),
      confidence: normalizeConfidence(summary.confidence),
    };

    deps.sendJson(res, {
      ok: true,
      available: true,
      latest: {
        timestamp: latest.timestamp,
        generatedAt: toStringValue(latest.payload.generatedAt, latest.timestamp),
        artifacts: {
          json: latest.fileName,
          markdown: `openclaw-local-smoke-${latest.timestamp}.md`,
          svg: `openclaw-local-smoke-${latest.timestamp}.svg`,
          markdownExists: fs.existsSync(path.join(deps.reportDir, `openclaw-local-smoke-${latest.timestamp}.md`)),
          svgExists: fs.existsSync(path.join(deps.reportDir, `openclaw-local-smoke-${latest.timestamp}.svg`)),
        },
        summary: summaryPayload,
        checksByGroup: summarizeGroups(checks),
        blockers: selectTopBlockers(checks),
      },
    });
    return true;
  } catch {
    deps.sendJson(res, { ok: false, available: false, error: 'Failed to read local readiness artifacts' }, 500);
    return true;
  }
}
