#!/usr/bin/env bash
# verify-conversation-pipeline.sh — VentureOS Conversation Pipeline Verification
#
# Bootstraps one real conversation through the production conversation ingest
# path and validates dashboard-visible outputs.
#
# Usage:
#   ./scripts/verify-conversation-pipeline.sh              # Run verification
#   ./scripts/verify-conversation-pipeline.sh --cleanup     # Remove verification data
#   ./scripts/verify-conversation-pipeline.sh --dry-run     # Show what would happen
#
# Prerequisites:
#   - Dashboard server running (default: http://localhost:3000)
#   - jq and curl available
#   - SQLite RPG database at $VENTUREOS_RPG_DB (default: ~/clawd/agents/ventureos-rpg.db)
#
# Environment:
#   DASHBOARD_URL       Dashboard base URL (default: http://localhost:3000)
#   VENTUREOS_RPG_DB    Path to RPG SQLite database
#   CONV_PERSIST_DIR    Conversation persist directory
#
# Fixes #183

set -euo pipefail

# ── Configuration ────────────────────────────────────────────────────────────

DASHBOARD_URL="${DASHBOARD_URL:-http://localhost:3000}"
RPG_DB="${VENTUREOS_RPG_DB:-${HOME}/clawd/agents/ventureos-rpg.db}"
PERSIST_DIR="${CONV_PERSIST_DIR:-${HOME}/clawd/ventureos/runtime/conversations}"
CONV_PREFIX="verify-pipeline"
SEED_INITIATOR="echo"
SEED_PARTICIPANTS='["echo", "nexus", "oracle"]'
CLEANUP=false
DRY_RUN=false
EXIT_CODE=0

# Parse flags
for arg in "$@"; do
  case "$arg" in
    --cleanup)  CLEANUP=true ;;
    --dry-run)  DRY_RUN=true ;;
    --help|-h)
      head -20 "$0" | grep '^#' | sed 's/^# \?//'
      exit 0
      ;;
  esac
done

# ── Helpers ──────────────────────────────────────────────────────────────────

pass()  { echo "  ✓ $*"; }
fail()  { echo "  ✗ $*"; EXIT_CODE=1; }
warn()  { echo "  ⚠ $*"; }
info()  { echo "  ℹ $*"; }
step()  { echo ""; echo "[$1] $2"; }

check_prereqs() {
  for cmd in curl jq sqlite3; do
    if ! command -v "$cmd" &>/dev/null; then
      echo "ERROR: '$cmd' is required but not found in PATH."
      exit 1
    fi
  done
}

# ── Cleanup Mode ─────────────────────────────────────────────────────────────

do_cleanup() {
  echo "=== VentureOS Conversation Pipeline — Cleanup ==="
  echo "RPG DB: ${RPG_DB}"
  echo "Persist dir: ${PERSIST_DIR}"

  if [ ! -f "$RPG_DB" ]; then
    echo "No RPG database found at ${RPG_DB}. Nothing to clean."
    exit 0
  fi

  # Find verification conversations by metadata tag
  local conv_ids
  conv_ids=$(sqlite3 "$RPG_DB" \
    "SELECT id FROM conversations WHERE metadata LIKE '%pipeline-verification%' OR metadata LIKE '%verify-script%';" 2>/dev/null || true)

  if [ -z "$conv_ids" ]; then
    echo "No verification conversations found. Nothing to clean."
    exit 0
  fi

  echo "Found verification conversations:"
  echo "$conv_ids" | while read -r cid; do echo "  - $cid"; done

  if [ "$DRY_RUN" = true ]; then
    echo "[dry-run] Would delete the above conversations and associated data."
    exit 0
  fi

  echo "$conv_ids" | while read -r cid; do
    sqlite3 "$RPG_DB" "DELETE FROM conversation_messages WHERE conversation_id = '${cid}';" 2>/dev/null || true
    sqlite3 "$RPG_DB" "DELETE FROM conversation_participants WHERE conversation_id = '${cid}';" 2>/dev/null || true
    sqlite3 "$RPG_DB" "DELETE FROM conversation_turn_state WHERE conversation_id = '${cid}';" 2>/dev/null || true
    sqlite3 "$RPG_DB" "DELETE FROM conversations WHERE id = '${cid}';" 2>/dev/null || true
    # Also remove interaction_logs generated by verify-script
    sqlite3 "$RPG_DB" "DELETE FROM interaction_logs WHERE session_id = '${cid}';" 2>/dev/null || true
    # Remove filesystem persistence file if it exists
    rm -f "${PERSIST_DIR}/${cid}.json" 2>/dev/null || true
    echo "  Removed: $cid"
  done

  echo "Cleanup complete."
  exit 0
}

if [ "$CLEANUP" = true ]; then
  check_prereqs
  do_cleanup
fi

# ── Main Verification Flow ───────────────────────────────────────────────────

echo "=== VentureOS Conversation Pipeline Verification ==="
echo "Dashboard: ${DASHBOARD_URL}"
echo "RPG DB:    ${RPG_DB}"
echo "Persist:   ${PERSIST_DIR}"
echo "Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

check_prereqs

if [ "$DRY_RUN" = true ]; then
  echo ""
  echo "[dry-run] Would perform 7-step verification against ${DASHBOARD_URL}"
  echo "[dry-run] Would create conversation with participants: ${SEED_PARTICIPANTS}"
  echo "[dry-run] Would send 2 verification messages"
  echo "[dry-run] Would verify SQLite persistence, API responses, and interaction logging"
  exit 0
fi

# ── Step 1: Check Dashboard Health ───────────────────────────────────────────

step "1/7" "Checking dashboard health..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 5 \
  "${DASHBOARD_URL}/api/conversation/conversations" 2>/dev/null || echo "000")

if [ "$HTTP_CODE" = "200" ]; then
  pass "Dashboard responding (HTTP ${HTTP_CODE})"
elif [ "$HTTP_CODE" = "401" ] || [ "$HTTP_CODE" = "403" ]; then
  # Auth might be enabled — try with cookie if available
  warn "Dashboard returned ${HTTP_CODE} (auth required). Checking with direct DB path instead."
  if [ ! -f "$RPG_DB" ]; then
    fail "Dashboard requires auth and no RPG DB found for direct verification."
    echo "Start the dashboard or ensure ${RPG_DB} exists."
    exit 1
  fi
  info "Will use direct SQLite verification instead of HTTP."
  DIRECT_DB_MODE=true
else
  fail "Dashboard not responding (HTTP ${HTTP_CODE})"
  echo "  Start the dashboard: cd ventureos && npm run dashboard:start"
  exit 1
fi

DIRECT_DB_MODE="${DIRECT_DB_MODE:-false}"

# ── Step 2: Check Persistence Infrastructure ─────────────────────────────────

step "2/7" "Checking persistence infrastructure..."

if [ ! -f "$RPG_DB" ]; then
  fail "RPG database not found: ${RPG_DB}"
  exit 1
fi
pass "RPG database exists: ${RPG_DB} ($(wc -c < "$RPG_DB" | tr -d ' ') bytes)"

# Verify tables exist
TABLE_CHECK=$(sqlite3 "$RPG_DB" \
  "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name IN ('conversations','conversation_messages','conversation_participants','conversation_turn_state','interaction_logs');" 2>/dev/null || echo "0")
if [ "$TABLE_CHECK" -ge 4 ]; then
  pass "Required tables present (${TABLE_CHECK}/5)"
else
  warn "Only ${TABLE_CHECK}/5 required tables found — tables will be auto-created on first use"
fi

if [ ! -d "$PERSIST_DIR" ]; then
  mkdir -p "$PERSIST_DIR"
  info "Created persist directory: ${PERSIST_DIR}"
fi
pass "Persist directory exists: ${PERSIST_DIR}"

# ── Step 3: Check for Existing Verification Conversation (Idempotent) ────────

step "3/7" "Creating verification conversation (idempotent)..."

# Check SQLite directly for existing verify-script conversations
EXISTING_ID=$(sqlite3 "$RPG_DB" \
  "SELECT id FROM conversations WHERE metadata LIKE '%pipeline-verification%' LIMIT 1;" 2>/dev/null || true)

if [ -n "$EXISTING_ID" ]; then
  info "Verification conversation already exists: ${EXISTING_ID}"
  CONV_ID="$EXISTING_ID"
  CREATED_NEW=false
else
  # Create via HTTP API
  if [ "$DIRECT_DB_MODE" = "true" ]; then
    fail "Cannot create conversation in direct-DB mode (no HTTP). Start the dashboard first."
    exit 1
  fi

  RESPONSE=$(curl -s -X POST "${DASHBOARD_URL}/api/conversation/conversations" \
    -H "Content-Type: application/json" \
    --max-time 10 \
    -d "{
      \"participants\": ${SEED_PARTICIPANTS},
      \"initiator\": \"${SEED_INITIATOR}\",
      \"metadata\": {
        \"purpose\": \"pipeline-verification\",
        \"created_by\": \"verify-script\",
        \"title\": \"Pipeline Verification Conversation\",
        \"created_at\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
      }
    }")

  CONV_ID=$(echo "$RESPONSE" | jq -r '.conversationId // empty')
  if [ -z "$CONV_ID" ]; then
    fail "Could not create conversation"
    echo "  Response: ${RESPONSE}"
    exit 1
  fi
  pass "Created conversation: ${CONV_ID}"
  CREATED_NEW=true
fi

# ── Step 4: Send Verification Messages ───────────────────────────────────────

step "4/7" "Sending verification messages..."

if [ "$DIRECT_DB_MODE" = "true" ]; then
  info "Skipping message send in direct-DB mode"
else
  # Get pre-message interaction count for later comparison
  PRE_INTERACTION_COUNT=$(sqlite3 "$RPG_DB" \
    "SELECT COUNT(*) FROM interaction_logs WHERE session_id = '${CONV_ID}';" 2>/dev/null || echo "0")

  # Message 1: From user → echo (user messages bypass handoff validation,
  # mirroring the real production ingest path)
  MSG1_RESPONSE=$(curl -s -X POST "${DASHBOARD_URL}/api/conversation/conversations/${CONV_ID}/messages" \
    -H "Content-Type: application/json" \
    --max-time 10 \
    -d '{
      "from": "user",
      "to": ["echo"],
      "content": "Pipeline verification message 1 — confirming ingest path is functional."
    }')

  MSG1_STATUS=$(echo "$MSG1_RESPONSE" | jq -r '.status // empty')
  if [ "$MSG1_STATUS" = "delivered" ]; then
    pass "Message 1 delivered (user → echo)"
  else
    warn "Message 1 status: ${MSG1_STATUS:-unknown}"
    info "Response: $(echo "$MSG1_RESPONSE" | jq -c '.' 2>/dev/null || echo "$MSG1_RESPONSE")"
  fi

  # Message 2: From user → nexus (second message to different participant)
  MSG2_RESPONSE=$(curl -s -X POST "${DASHBOARD_URL}/api/conversation/conversations/${CONV_ID}/messages" \
    -H "Content-Type: application/json" \
    --max-time 10 \
    -d '{
      "from": "user",
      "to": ["nexus"],
      "content": "Pipeline verification message 2 — confirming multi-participant routing."
    }')

  MSG2_STATUS=$(echo "$MSG2_RESPONSE" | jq -r '.status // empty')
  if [ "$MSG2_STATUS" = "delivered" ]; then
    pass "Message 2 delivered (user → nexus)"
  else
    warn "Message 2 status: ${MSG2_STATUS:-unknown}"
    info "Response: $(echo "$MSG2_RESPONSE" | jq -c '.' 2>/dev/null || echo "$MSG2_RESPONSE")"
  fi
fi

# ── Step 5: Verify SQLite Persistence ────────────────────────────────────────

step "5/7" "Verifying SQLite persistence..."

# Check conversations table
CONV_ROW=$(sqlite3 "$RPG_DB" \
  "SELECT id, status, title FROM conversations WHERE id = '${CONV_ID}';" 2>/dev/null || true)

if [ -n "$CONV_ROW" ]; then
  pass "Conversation found in SQLite: ${CONV_ROW}"
else
  fail "Conversation ${CONV_ID} not found in conversations table"
fi

# Check messages
MSG_COUNT=$(sqlite3 "$RPG_DB" \
  "SELECT COUNT(*) FROM conversation_messages WHERE conversation_id = '${CONV_ID}';" 2>/dev/null || echo "0")

if [ "$MSG_COUNT" -ge 1 ]; then
  pass "Messages persisted: ${MSG_COUNT} message(s) in conversation_messages"
else
  if [ "$DIRECT_DB_MODE" = "true" ] || [ "$CREATED_NEW" = "false" ]; then
    info "Message count: ${MSG_COUNT} (expected if no new messages were sent)"
  else
    fail "No messages found in conversation_messages for ${CONV_ID}"
  fi
fi

# Check participants
PART_COUNT=$(sqlite3 "$RPG_DB" \
  "SELECT COUNT(*) FROM conversation_participants WHERE conversation_id = '${CONV_ID}';" 2>/dev/null || echo "0")

if [ "$PART_COUNT" -ge 2 ]; then
  pass "Participants persisted: ${PART_COUNT} participants"
else
  fail "Expected ≥2 participants, found ${PART_COUNT}"
fi

# Check turn state
TURN_SPEAKER=$(sqlite3 "$RPG_DB" \
  "SELECT current_speaker FROM conversation_turn_state WHERE conversation_id = '${CONV_ID}';" 2>/dev/null || true)

if [ -n "$TURN_SPEAKER" ]; then
  pass "Turn state persisted: current_speaker=${TURN_SPEAKER}"
else
  warn "No turn state found for ${CONV_ID}"
fi

# Check filesystem persistence
if [ -f "${PERSIST_DIR}/${CONV_ID}.json" ]; then
  FILE_SIZE=$(wc -c < "${PERSIST_DIR}/${CONV_ID}.json" | tr -d ' ')
  pass "Filesystem persistence: ${PERSIST_DIR}/${CONV_ID}.json (${FILE_SIZE} bytes)"
else
  info "No filesystem persistence file (SQLite store is primary — this is expected)"
fi

# ── Step 6: Verify API Responses ─────────────────────────────────────────────

step "6/7" "Verifying API list responses..."

if [ "$DIRECT_DB_MODE" = "true" ]; then
  # Direct DB check
  CONV_LIST_COUNT=$(sqlite3 "$RPG_DB" "SELECT COUNT(*) FROM conversations;" 2>/dev/null || echo "0")
  if [ "$CONV_LIST_COUNT" -ge 1 ]; then
    pass "Conversations in database: ${CONV_LIST_COUNT}"
  else
    fail "No conversations found in database"
  fi
else
  # Check /api/conversation/conversations
  LIST_RESPONSE=$(curl -s --max-time 10 "${DASHBOARD_URL}/api/conversation/conversations")
  FOUND=$(echo "$LIST_RESPONSE" | jq -r ".conversations[]" 2>/dev/null | grep "^${CONV_ID}$" || true)

  if [ -n "$FOUND" ]; then
    pass "/api/conversation/conversations includes ${CONV_ID}"
  else
    fail "Conversation ${CONV_ID} not in /api/conversation/conversations response"
    info "Response: $(echo "$LIST_RESPONSE" | jq -c '.' 2>/dev/null || echo "$LIST_RESPONSE")"
  fi

  # Check /api/rpg/conversations/active
  ACTIVE_RESPONSE=$(curl -s --max-time 10 "${DASHBOARD_URL}/api/rpg/conversations/active")
  ACTIVE_COUNT=$(echo "$ACTIVE_RESPONSE" | jq '.conversations | length' 2>/dev/null || echo "0")

  if [ "$ACTIVE_COUNT" -gt 0 ]; then
    ACTIVE_FOUND=$(echo "$ACTIVE_RESPONSE" | jq -r ".conversations[].id" 2>/dev/null | grep "^${CONV_ID}$" || true)
    if [ -n "$ACTIVE_FOUND" ]; then
      pass "/api/rpg/conversations/active includes ${CONV_ID} (${ACTIVE_COUNT} total)"
    else
      warn "/api/rpg/conversations/active has ${ACTIVE_COUNT} conversations but ${CONV_ID} not found"
    fi
  else
    warn "/api/rpg/conversations/active returned 0 conversations"
    info "Response: $(echo "$ACTIVE_RESPONSE" | jq -c '.' 2>/dev/null || echo "$ACTIVE_RESPONSE")"
  fi
fi

# ── Step 7: Verify Interaction Logging ───────────────────────────────────────

step "7/7" "Verifying interaction logging..."

POST_INTERACTION_COUNT=$(sqlite3 "$RPG_DB" \
  "SELECT COUNT(*) FROM interaction_logs WHERE session_id = '${CONV_ID}';" 2>/dev/null || echo "0")

if [ "$POST_INTERACTION_COUNT" -ge 1 ]; then
  pass "Interaction logs: ${POST_INTERACTION_COUNT} entries for conversation ${CONV_ID}"
  # Show sample
  SAMPLE=$(sqlite3 "$RPG_DB" \
    "SELECT initiator_agent || ' → ' || recipient_agent || ' (' || interaction_type || ')' FROM interaction_logs WHERE session_id = '${CONV_ID}' LIMIT 3;" 2>/dev/null || true)
  if [ -n "$SAMPLE" ]; then
    echo "$SAMPLE" | while read -r line; do info "  $line"; done
  fi
else
  if [ "$DIRECT_DB_MODE" = "true" ]; then
    info "Interaction log count: ${POST_INTERACTION_COUNT} (expected in direct-DB mode)"
  else
    # Check if interaction delta occurred
    PRE_INTERACTION_COUNT="${PRE_INTERACTION_COUNT:-0}"
    TOTAL_INTERACTIONS=$(sqlite3 "$RPG_DB" \
      "SELECT COUNT(*) FROM interaction_logs;" 2>/dev/null || echo "0")
    if [ "$TOTAL_INTERACTIONS" -gt "$PRE_INTERACTION_COUNT" ]; then
      pass "Total interaction log count increased (now ${TOTAL_INTERACTIONS})"
    else
      warn "No interaction logs found for ${CONV_ID} (total: ${TOTAL_INTERACTIONS})"
    fi
  fi
fi

# ── Summary ──────────────────────────────────────────────────────────────────

echo ""
echo "=== Pipeline Verification Complete ==="
echo "Conversation ID: ${CONV_ID}"
echo "Created new:     ${CREATED_NEW:-unknown}"

if [ "$EXIT_CODE" -eq 0 ]; then
  echo "Result:          ALL CHECKS PASSED ✓"
else
  echo "Result:          SOME CHECKS FAILED ✗"
fi

echo ""
echo "Cleanup: ./scripts/verify-conversation-pipeline.sh --cleanup"
exit "$EXIT_CODE"
